config/routes.rb
WeymanPort::Application.routes.draw do
  resources :static
  get "/home", to: "static#home"
  get "/asteroids", to: "static#asteroids"
  get "/snake", to: "static#snake"
  root to: "static#home"

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    
  end

  def asteroids

  end
  
  def snake
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weyman Fung</title>
  <link rel="shortcut icon" href="/assets/title.ico"/>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
	<a name="top"></a>
<body>
	
	<div class="jumbotron">
		<div class="logo">
		<%= link_to image_tag("weyman_logo.png"), home_url %>
		</div>
		<a href="http://github.com/weymanf" class="pop"><%= image_tag("github.png") %></a>
		<a href="http://www.linkedin.com/pub/weyman-fung/75/173/626" class="pop"><%= image_tag("linked.png") %></a>
		<%= link_to image_tag("resume.png"), "fung_resume.pdf", :class => "pop" %>
		<div class="btn-group games">
  			<a class="btn dropdown-toggle games" data-toggle="dropdown">
    		Game Portal
    		<span class="caret"></span>
 			</a>
  		<ul class="dropdown-menu">
    		<li><%= link_to "Asteroids", asteroids_url %>
			<li><%= link_to "Snake", snake_url %>
  		</ul>
		</div>
		
	</div>


<%= yield %>

	
	<div class="bottom">
		<h3>  Weyman © 2014   </h3>
		<a href="#top">Back to Top</a>
	</div>

</body>
</html>